# Generated by Django 3.1.7 on 2021-04-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('resource_path', models.CharField(max_length=1028)),
                ('short_code', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('visit_limit', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
